name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.13.5"
      POETRY_VERSION: "2.1.3"
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} 

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        run: pip install poetry==${{ env.POETRY_VERSION }}

      - name: Install deps (no‑root)
        run: |
          poetry install --no-root --with dev
          echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

      - name: Run tests
        run: poetry run pytest